# ------------------ APP ------------------
spring.application.name=Velora
server.port=${PORT:8080}

# ------------------ DATABASE ------------------
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ------------------ GEMINI AI ------------------
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

# ------------------ MAIL ------------------
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}

spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE}

# ------------------ RAZORPAY ------------------
razorpay.key=${RAZORPAY_KEY}
razorpay.secret=${RAZORPAY_SECRET}
#server.forward-headers-strategy=framework
